home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home_view"),
    path('save_image/', views.save_image, name='save_image'),
    path("extract-user-data/", views.ExtractUserDataView.as_view(), name="extract_user_data")
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.urls import re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.index_title = "NNDC Business and Traders Support Scheme"
admin.site.site_header = "NNDC Business and Traders Support Scheme Admin"
admin.site.site_title = "NNDC Business and Traders Support Scheme Adminiistration"

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from cloudinary.models import CloudinaryField

# Create your models here.

class ApplicantDetail(models.Model):
    applicant_image = CloudinaryField('image', blank=True, null=True)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    tradeType = models.CharField(max_length=255)
    accountNumber = models.CharField(max_length=255)
    bankName = models.CharField(max_length=255)
    phoneNumber = models.CharField(max_length=255)
    lga = models.CharField(max_length=255)
    albumSerialNumber = models.IntegerField(blank=True, null=True)
    employmentStrength = models.CharField(max_length=255, blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = ("Applicant Details")
        verbose_name_plural = ("Applicant Details")
        ordering = ("albumSerialNumber",)

    def __str__(self):
        return f"{self.first_name} {self.last_name} details"

home/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.http import JsonResponse
from .models import ApplicantDetail
from django.core.files.base import ContentFile
import base64
from django.contrib import messages
import cloudinary.uploader
import pandas as pd
from django.http import FileResponse


# Create your views here.

class HomeView(View):
    def get(self, request, *args, **kwargs):
        return render(request, "home/index.html")
    
    def post(self, request, *args, **kwargs):
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        tradeType = request.POST.get("tradeType")
        accountNumber = request.POST.get("accountNumber")
        bankName = request.POST.get("bankName")
        lga = request.POST.get("lga")
        albumSerialNumber = int(request.POST.get("albumSerialNumber"))
        phoneNumber = request.POST.get("phoneNumber")
        employmentStrength = request.POST.get("employmentStrength")
        print(first_name)
        print(last_name)
        print(tradeType)
        print(accountNumber)
        print(bankName)
        print(lga)
        print(phoneNumber)
        print(employmentStrength)
        context = {
            "first_name":first_name,
            "last_name":last_name,
            "tradeType":tradeType,
            "accountNumber":accountNumber,
            "bankName":bankName,
            "lga":lga,
            "albumSerialNumber":albumSerialNumber,
            "phoneNumber":phoneNumber,
            "employmentStrength":employmentStrength
        }
        return render(request, "home/capture-image.html", context)
        

def save_image(request):
    if request.method == 'POST':
        image_data = request.POST.get('image_data')
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        tradeType = request.POST.get("tradeType")
        accountNumber = request.POST.get("accountNumber")
        bankName = request.POST.get("bankName")
        lga = request.POST.get("lga")
        albumSerialNumber = int(request.POST.get("albumSerialNumber"))
        phoneNumber = request.POST.get("phoneNumber")
        employmentStrength = request.POST.get("employmentStrength")

        # Convert Base64 data to image file
        format, imgstr = image_data.split(';base64,')
        ext = format.split('/')[-1]
        image_file = ContentFile(base64.b64decode(imgstr), name=f'image.{ext}')

        folder_name = 'applicant_photo'  # Specify the folder name here
        # Upload image to Cloudinary with folder specified
        upload_result = cloudinary.uploader.upload(image_file, folder=folder_name)
        image_url = upload_result['secure_url']

        # # Create a new Image instance and save it to the database
        new_applicant = ApplicantDetail(applicant_image=image_url, employmentStrength=employmentStrength, phoneNumber=phoneNumber, albumSerialNumber=albumSerialNumber, first_name=first_name, last_name=last_name, tradeType=tradeType, accountNumber=accountNumber, bankName=bankName, lga=lga)
        new_applicant.save()
        messages.success(request, 'Applicant Registered Successfully')
        return JsonResponse({'success': True})
    return JsonResponse({'success': False})


class ExtractUserDataView(View):
    def get(self, request, *args, **kwargs):
        # Retrieve data from Django database
        data = ApplicantDetail.objects.all().order_by("albumSerialNumber")

        # Convert data to a Pandas DataFrame
        data_df = pd.DataFrame(list(data.values()))

        # Drop the field(s) you want to exclude
        data_df = data_df.drop(["applicant_image", "timestamp", "id"], axis=1)

        # Export DataFrame to spreadsheet
        output_path = 'output.xlsx'
        data_df.to_excel(output_path, index=False)

        # Serve the file as a response for download
        response = FileResponse(open(output_path, 'rb'), as_attachment=True)
        response['Content-Disposition'] = 'attachment; filename="output.xlsx"'
        return response

home/templates/home/capture-image.html
{% csrf_token %}
<!DOCTYPE html>
<html>
<head>
    <title>Take Picture</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <h1>Take a Picture</h1>
    <div id="camera-container">
        <video id="camera-stream" autoplay></video>
        <button id="capture-btn">Capture</button>
    </div>


    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <script>
        // Access the webcam and display the video stream
        navigator.mediaDevices.getUserMedia({ video: true })
            .then(function (stream) {
                var video = document.getElementById('camera-stream');
                video.srcObject = stream;
                video.play();
            })
            .catch(function (error) {
                console.log('Unable to access the camera stream:', error);
            });

        // Capture the image from the video stream
        var captureBtn = document.getElementById('capture-btn');
        captureBtn.addEventListener('click', function () {
            var video = document.getElementById('camera-stream');
            var canvas = document.createElement('canvas');
            var context = canvas.getContext('2d');
            canvas.width = video.videoWidth;
            canvas.height = video.videoHeight;
            context.drawImage(video, 0, 0, canvas.width, canvas.height);
            var imageData = canvas.toDataURL('image/png');

            const csrfToken = document.getElementsByName("csrfmiddlewaretoken")[0].value;
            $.ajax({
                url: "{% url 'home:save_image' %}",
                type: 'POST',
                dataType: 'json',
                headers: { 'X-CSRFToken': csrfToken },
                data: { 'image_data': imageData, "employmentStrength":"{{ employmentStrength }}", "phoneNumber":"{{ phoneNumber }}", "albumSerialNumber":"{{ albumSerialNumber }}", "first_name":"{{ first_name }}", "last_name":"{{ last_name }}", "tradeType":"{{ tradeType }}", "accountNumber":"{{ accountNumber }}", "bankName":"{{ bankName }}", "lga":"{{ lga }}"}, // Include the image data in the AJAX request
                success: function (data) {
                    if (data.success === true) {
                        window.location.href = "{% url 'home:home_view' %}";
                    } else {
                        console.log("Error removing attendee:", data.message);
                    }
                },
                error: function (xhr, status, error) {
                    console.log("Error removing attendee:", error);
                }
            });
        });
    </script>
</body>
</html>

home/templates/home/index.html
<!DOCTYPE html>
<html>
<head>
  <title>NNDC Business and Traders Support Scheme - Applicant Enrollment</title>
  <!-- Include Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <!-- Custom CSS -->
  <style>
    /* Add your custom styles here */
    .logo {
      height: 100px;
      width: 100px;
      /* Add your logo styles here */
    }
    .form-container {
      max-width: 700px;
      margin: 0 auto;
      /* Add your form container styles here */
    }
  </style>
</head>
<body>
  <!-- Logo -->
  <!-- <div class="text-center">
    <img src="#" alt="Logo" class="logo">
  </div> -->
  

  {% for message in messages %}
    <div class="alert alert-{{ message.tags }} mb-0 alert-dismissible fade show" role="alert">
      <strong>Message: </strong> {{ message }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  {% endfor %}
  
  <!-- Form -->
  <div class="container form-container">
    <h2 class="text-center">NNDC Business and Traders Support Scheme</h2>
    <h4 class="text-center">Applicant Enrollment</h4>
    <form class="m-5" method="post">
      {% csrf_token %}
      <div class="form-row mb-2">
        <div class="col-md-6">
          <label for="name">First Name</label>
          <input type="text" class="form-control" id="name" placeholder="Enter your first name" name="first_name" required>
        </div>
        <div class="col-md-6">
          <label for="name">Last Name</label>
          <input type="text" class="form-control" id="name" placeholder="Enter your last name" name="last_name" required>
        </div>
      </div>
      <div class="form-group">
        <label for="tradeType">Trade Type</label>
        <input type="text" class="form-control" id="tradeType" placeholder="Enter your trade type" name="tradeType" required>
      </div>
      <div class="form-group">
        <label for="accountNumber">Account Number</label>
        <input type="number" class="form-control" id="accountNumber" placeholder="Enter your account number" name="accountNumber" required>
      </div>
      <div class="form-group">
        <label for="bankName">Bank Name</label>
        <select class="form-control" id="bankName" name="bankName" required>
          <option value="">Select Bank</option>
          <option value="United Bank for Africa PLC">United Bank for Africa PLC</option>
          <option value="First Bank of Nigeria Limited">First Bank of Nigeria Limited</option>
          <option value="Zenith Bank PLC">Zenith Bank PLC</option>
          <option value="Union Bank of Nigeria PLC">Union Bank of Nigeria PLC</option>
          <option value="Guaranty Trust Bank">Guaranty Trust Bank</option>
          <option value="Fidelity Bank PLC">Fidelity Bank PLC</option>
          <option value="Keystone Bank Limited">Keystone Bank Limited</option>
          <option value="Ecobank Nigeria">Ecobank Nigeria</option>
          <option value="Wema Bank PLC">Wema Bank PLC</option>
          <option value="Access Bank Plc">Access Bank Plc</option>
          <option value="First City Monument Bank Limited">First City Monument Bank Limited</option>
          <option value="Polaris Bank Limited">Polaris Bank Limited</option>
          <option value="Sterling Bank PLC">Sterling Bank PLC</option>
          <option value="Unity Bank plc">Unity Bank plc</option>
          <option value="Stanbic IBTC Bank PLC">Stanbic IBTC Bank PLC</option>
        </select>
      </div>
      <div class="form-group">
        <label for="tradeType">Phone Number</label>
        <input type="number" class="form-control" id="phoneNumber" placeholder="Enter your Phone Number" name="phoneNumber" required>
      </div>
      <div class="form-group">
        <label for="albumSerialNumber">Employment Strength</label>
        <input type="text" class="form-control" id="employmentStrength" placeholder="Enter your Employment Strength" required name="employmentStrength">
      </div>
      <div class="form-group">
        <label for="albumSerialNumber">Album Serial Number</label>
        <input type="number" class="form-control" id="albumSerialNumber" placeholder="Enter your album serial number" required name="albumSerialNumber">
      </div>
      <div class="form-group">
        <label for="lga">LGA</label>
        <select class="form-control" id="lga" name="lga" required>
          <option value="">Select LGA</option>
          <option value="Abak">Abak</option>
          <option value="Eastern Obolo">Eastern Obolo</option>
          <option value="Eket">Eket</option>
          <option value="Esit Eket">Esit Eket</option>
          <option value="Essien Udim">Essien Udim</option>
          <option value="Etim Ekpo">Etim Ekpo</option>
          <option value="Etinan">Etinan</option>
          <option value="Ibeno">Ibeno</option>
          <option value="Ibesikpo Asutan">Ibesikpo Asutan</option>
          <option value="Ibiono Ibom">Ibiono Ibom</option>
          <option value="Ika">Ika</option>
          <option value="Ikono">Ikono</option>
          <option value="Ikot Abasi">Ikot Abasi</option>
          <option value="Ikot Ekpene">Ikot Ekpene</option>
          <option value="Ini">Ini</option>
          <option value="Itu">Itu</option>
          <option value="Mbo">Mbo</option>
          <option value="Mkpat Enin">Mkpat Enin</option>
          <option value="Nsit Atai">Nsit Atai</option>
          <option value="Nsit Ibom">Nsit Ibom</option>
          <option value="Nsit Ubium">Nsit Ubium</option>
          <option value="Obot Akara">Obot Akara</option>
          <option value="Okobo">Okobo</option>
          <option value="Onna">Onna</option>
          <option value="Oron">Oron</option>
          <option value="Oruk Anam">Oruk Anam</option>
          <option value="Udung Uko">Udung Uko</option>
          <option value="Ukanafun">Ukanafun</option>
          <option value="Uruan">Uruan</option>
          <option value="Urue-Offong/Oruko">Urue-Offong/Oruko</option>
          <option value="Uyo">Uyo</option>
        </select>
      </div>
      <div class="form-row">
        <div class="col-md-6">
          <button type="submit" class="btn btn-primary" style="width: 100%;">Next</button>
        </div>
        <div class="col-md-6">
          <a class="btn btn-success" href="{% url 'home:extract_user_data' %}" style="width: 100%;">Extract Users Data</a>
        </div>
      </div>
    </form>
  </div>
  
  <!-- Include Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>